### PR TITLE
Add Maemos 1–5

### LINKED ISSUE #22: Add Maemo
The Nokia N900 OS was Maemo 5, or Maemo Fremantle if you prefer. (I prefer Fremantle because I had to look up the number while the codename is firmly imprinted in my memory.) Here is a CC screenshot I found in 30 seconds on the Elizabeth Line. https://www.flickr.com/photos/panaggio/4036987071/ The N900 had a hardware keyboard, with arrow keys, and shipped with a terminal emulator and Debian package management so is clearly a computer not a phone.

There were previous Maemo:s. They were all landscape oriented too. N810 had a hardware keyboard and dpkg so again, it's a computer and Lex would know how to use it.

(Fremantle's successor, Meego Harmattan on the N9, was primarily portrait-orientation so doesn't fit the template.)

### PR DESCRIPTION
**Pull request by wjt**
Fixes #22

### CODE REVIEW

**Comment by fooishbar** [comment]
Maemos 1-4 are more correctly referred to as 'Internet Tablet OS'; Fremantle was the first time Maemo was a thing, with 5 being retconned from there having been ITOS 200{5,7,8,8+}. (IIRC, originally ITOS 2005 was itself a retcon as ITOS was originally unversioned, and 2007 was referred to as 'Sputnik+' until they realised they needed a better name for public release.)

Congratulations on submitting a pull request however.

**Comment by wjt** [comment]
Thanks again @fooishbar. I have updated the PR based on your feedback, and also added Maemo Leste, the premier Devuan-based OS for obsolete smartphones.

**Comment by fooishbar** [comment]
```
<presence from=“fooishbar@github.com/review” to=“wjt@github.com”>
  <status>in favour</status>
  <show>a magnificent contribution</show>
</presence>
```

**Comment by dill** [comment]
tusen takk @wjt & @fooishbar

**Pull request merged**
